/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopUpgradeRouteImport } from './routes/shop.upgrade'
import { Route as ShopStaffRouteImport } from './routes/shop.staff'
import { Route as ShopSettingsRouteImport } from './routes/shop.settings'
import { Route as ShopServicesRouteImport } from './routes/shop.services'
import { Route as ShopPaymentsRouteImport } from './routes/shop.payments'
import { Route as ShopNotificationsRouteImport } from './routes/shop.notifications'
import { Route as ShopCustomersRouteImport } from './routes/shop.customers'
import { Route as ShopCalendarRouteImport } from './routes/shop.calendar'
import { Route as ShopBillingRouteImport } from './routes/shop.billing'
import { Route as ShopAnalyticsRouteImport } from './routes/shop.analytics'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as HooksBookingConfirmationRouteImport } from './routes/hooks/booking-confirmation'
import { Route as HooksBookingAutomationsRouteImport } from './routes/hooks/booking-automations'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as BeheerDashboardIndexRouteImport } from './routes/beheer.dashboard.index'
import { Route as ShopCustomersCustomerIdRouteImport } from './routes/shop.customers.$customerId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as BookConfirmationBookingIdRouteImport } from './routes/book.confirmation.$bookingId'
import { Route as BeheerDashboardUsersRouteImport } from './routes/beheer.dashboard.users'
import { Route as BeheerDashboardSupportRouteImport } from './routes/beheer.dashboard.support'
import { Route as BeheerDashboardShopsRouteImport } from './routes/beheer.dashboard.shops'
import { Route as BeheerDashboardSettingsRouteImport } from './routes/beheer.dashboard.settings'
import { Route as BeheerDashboardProvidersRouteImport } from './routes/beheer.dashboard.providers'
import { Route as BeheerDashboardPlansRouteImport } from './routes/beheer.dashboard.plans'
import { Route as BeheerDashboardPaymentsRouteImport } from './routes/beheer.dashboard.payments'
import { Route as BeheerDashboardMessagesRouteImport } from './routes/beheer.dashboard.messages'
import { Route as BeheerDashboardLogsRouteImport } from './routes/beheer.dashboard.logs'
import { Route as BeheerDashboardDemoRouteImport } from './routes/beheer.dashboard.demo'
import { Route as BeheerDashboardBookingsRouteImport } from './routes/beheer.dashboard.bookings'
import { Route as BeheerDashboardBillingRouteImport } from './routes/beheer.dashboard.billing'
import { Route as BeheerAdLoginRouteImport } from './routes/beheer.ad.login'
import { Route as ApiMollieWebhookRouteImport } from './routes/api.mollie.webhook'
import { Route as ApiBillingPlanConfirmRouteImport } from './routes/api.billing.plan-confirm'
import { Route as ApiBillingPlanCheckoutRouteImport } from './routes/api.billing.plan-checkout'
import { Route as ApiBillingExpireSweepRouteImport } from './routes/api.billing.expire-sweep'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopUpgradeRoute = ShopUpgradeRouteImport.update({
  id: '/shop/upgrade',
  path: '/shop/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopStaffRoute = ShopStaffRouteImport.update({
  id: '/shop/staff',
  path: '/shop/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSettingsRoute = ShopSettingsRouteImport.update({
  id: '/shop/settings',
  path: '/shop/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopServicesRoute = ShopServicesRouteImport.update({
  id: '/shop/services',
  path: '/shop/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPaymentsRoute = ShopPaymentsRouteImport.update({
  id: '/shop/payments',
  path: '/shop/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopNotificationsRoute = ShopNotificationsRouteImport.update({
  id: '/shop/notifications',
  path: '/shop/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCustomersRoute = ShopCustomersRouteImport.update({
  id: '/shop/customers',
  path: '/shop/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCalendarRoute = ShopCalendarRouteImport.update({
  id: '/shop/calendar',
  path: '/shop/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBillingRoute = ShopBillingRouteImport.update({
  id: '/shop/billing',
  path: '/shop/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAnalyticsRoute = ShopAnalyticsRouteImport.update({
  id: '/shop/analytics',
  path: '/shop/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksBookingConfirmationRoute =
  HooksBookingConfirmationRouteImport.update({
    id: '/hooks/booking-confirmation',
    path: '/hooks/booking-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksBookingAutomationsRoute = HooksBookingAutomationsRouteImport.update({
  id: '/hooks/booking-automations',
  path: '/hooks/booking-automations',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardIndexRoute = BeheerDashboardIndexRouteImport.update({
  id: '/beheer/dashboard/',
  path: '/beheer/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCustomersCustomerIdRoute = ShopCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => ShopCustomersRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmationBookingIdRoute =
  BookConfirmationBookingIdRouteImport.update({
    id: '/confirmation/$bookingId',
    path: '/confirmation/$bookingId',
    getParentRoute: () => BookRoute,
  } as any)
const BeheerDashboardUsersRoute = BeheerDashboardUsersRouteImport.update({
  id: '/beheer/dashboard/users',
  path: '/beheer/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardSupportRoute = BeheerDashboardSupportRouteImport.update({
  id: '/beheer/dashboard/support',
  path: '/beheer/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardShopsRoute = BeheerDashboardShopsRouteImport.update({
  id: '/beheer/dashboard/shops',
  path: '/beheer/dashboard/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardSettingsRoute = BeheerDashboardSettingsRouteImport.update({
  id: '/beheer/dashboard/settings',
  path: '/beheer/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardProvidersRoute =
  BeheerDashboardProvidersRouteImport.update({
    id: '/beheer/dashboard/providers',
    path: '/beheer/dashboard/providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const BeheerDashboardPlansRoute = BeheerDashboardPlansRouteImport.update({
  id: '/beheer/dashboard/plans',
  path: '/beheer/dashboard/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardPaymentsRoute = BeheerDashboardPaymentsRouteImport.update({
  id: '/beheer/dashboard/payments',
  path: '/beheer/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardMessagesRoute = BeheerDashboardMessagesRouteImport.update({
  id: '/beheer/dashboard/messages',
  path: '/beheer/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardLogsRoute = BeheerDashboardLogsRouteImport.update({
  id: '/beheer/dashboard/logs',
  path: '/beheer/dashboard/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardDemoRoute = BeheerDashboardDemoRouteImport.update({
  id: '/beheer/dashboard/demo',
  path: '/beheer/dashboard/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardBookingsRoute = BeheerDashboardBookingsRouteImport.update({
  id: '/beheer/dashboard/bookings',
  path: '/beheer/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardBillingRoute = BeheerDashboardBillingRouteImport.update({
  id: '/beheer/dashboard/billing',
  path: '/beheer/dashboard/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerAdLoginRoute = BeheerAdLoginRouteImport.update({
  id: '/beheer/ad/login',
  path: '/beheer/ad/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMollieWebhookRoute = ApiMollieWebhookRouteImport.update({
  id: '/api/mollie/webhook',
  path: '/api/mollie/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlanConfirmRoute = ApiBillingPlanConfirmRouteImport.update({
  id: '/api/billing/plan-confirm',
  path: '/api/billing/plan-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlanCheckoutRoute = ApiBillingPlanCheckoutRouteImport.update({
  id: '/api/billing/plan-checkout',
  path: '/api/billing/plan-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingExpireSweepRoute = ApiBillingExpireSweepRouteImport.update({
  id: '/api/billing/expire-sweep',
  path: '/api/billing/expire-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/booking-automations': typeof HooksBookingAutomationsRoute
  '/hooks/booking-confirmation': typeof HooksBookingConfirmationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/billing': typeof ShopBillingRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRouteWithChildren
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop/upgrade': typeof ShopUpgradeRoute
  '/shop/': typeof ShopIndexRoute
  '/api/billing/expire-sweep': typeof ApiBillingExpireSweepRoute
  '/api/billing/plan-checkout': typeof ApiBillingPlanCheckoutRoute
  '/api/billing/plan-confirm': typeof ApiBillingPlanConfirmRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/billing': typeof BeheerDashboardBillingRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/demo': typeof BeheerDashboardDemoRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/messages': typeof BeheerDashboardMessagesRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/providers': typeof BeheerDashboardProvidersRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/customers/$customerId': typeof ShopCustomersCustomerIdRoute
  '/beheer/dashboard/': typeof BeheerDashboardIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/booking-automations': typeof HooksBookingAutomationsRoute
  '/hooks/booking-confirmation': typeof HooksBookingConfirmationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/billing': typeof ShopBillingRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRouteWithChildren
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop/upgrade': typeof ShopUpgradeRoute
  '/shop': typeof ShopIndexRoute
  '/api/billing/expire-sweep': typeof ApiBillingExpireSweepRoute
  '/api/billing/plan-checkout': typeof ApiBillingPlanCheckoutRoute
  '/api/billing/plan-confirm': typeof ApiBillingPlanConfirmRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/billing': typeof BeheerDashboardBillingRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/demo': typeof BeheerDashboardDemoRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/messages': typeof BeheerDashboardMessagesRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/providers': typeof BeheerDashboardProvidersRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/customers/$customerId': typeof ShopCustomersCustomerIdRoute
  '/beheer/dashboard': typeof BeheerDashboardIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/booking-automations': typeof HooksBookingAutomationsRoute
  '/hooks/booking-confirmation': typeof HooksBookingConfirmationRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/billing': typeof ShopBillingRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRouteWithChildren
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop/upgrade': typeof ShopUpgradeRoute
  '/shop/': typeof ShopIndexRoute
  '/api/billing/expire-sweep': typeof ApiBillingExpireSweepRoute
  '/api/billing/plan-checkout': typeof ApiBillingPlanCheckoutRoute
  '/api/billing/plan-confirm': typeof ApiBillingPlanConfirmRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/billing': typeof BeheerDashboardBillingRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/demo': typeof BeheerDashboardDemoRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/messages': typeof BeheerDashboardMessagesRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/providers': typeof BeheerDashboardProvidersRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/customers/$customerId': typeof ShopCustomersCustomerIdRoute
  '/beheer/dashboard/': typeof BeheerDashboardIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/login'
    | '/signup'
    | '/support'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/email/unsubscribe'
    | '/hooks/booking-automations'
    | '/hooks/booking-confirmation'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/shop/analytics'
    | '/shop/billing'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop/upgrade'
    | '/shop/'
    | '/api/billing/expire-sweep'
    | '/api/billing/plan-checkout'
    | '/api/billing/plan-confirm'
    | '/api/mollie/webhook'
    | '/beheer/ad/login'
    | '/beheer/dashboard/billing'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/demo'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/messages'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/providers'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/lovable/email/suppression'
    | '/shop/customers/$customerId'
    | '/beheer/dashboard/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/signup'
    | '/support'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/email/unsubscribe'
    | '/hooks/booking-automations'
    | '/hooks/booking-confirmation'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/shop/analytics'
    | '/shop/billing'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop/upgrade'
    | '/shop'
    | '/api/billing/expire-sweep'
    | '/api/billing/plan-checkout'
    | '/api/billing/plan-confirm'
    | '/api/mollie/webhook'
    | '/beheer/ad/login'
    | '/beheer/dashboard/billing'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/demo'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/messages'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/providers'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/lovable/email/suppression'
    | '/shop/customers/$customerId'
    | '/beheer/dashboard'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/login'
    | '/signup'
    | '/support'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/email/unsubscribe'
    | '/hooks/booking-automations'
    | '/hooks/booking-confirmation'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/shop/analytics'
    | '/shop/billing'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop/upgrade'
    | '/shop/'
    | '/api/billing/expire-sweep'
    | '/api/billing/plan-checkout'
    | '/api/billing/plan-confirm'
    | '/api/mollie/webhook'
    | '/beheer/ad/login'
    | '/beheer/dashboard/billing'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/demo'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/messages'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/providers'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/lovable/email/suppression'
    | '/shop/customers/$customerId'
    | '/beheer/dashboard/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  HooksBookingAutomationsRoute: typeof HooksBookingAutomationsRoute
  HooksBookingConfirmationRoute: typeof HooksBookingConfirmationRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ShopAnalyticsRoute: typeof ShopAnalyticsRoute
  ShopBillingRoute: typeof ShopBillingRoute
  ShopCalendarRoute: typeof ShopCalendarRoute
  ShopCustomersRoute: typeof ShopCustomersRouteWithChildren
  ShopNotificationsRoute: typeof ShopNotificationsRoute
  ShopPaymentsRoute: typeof ShopPaymentsRoute
  ShopServicesRoute: typeof ShopServicesRoute
  ShopSettingsRoute: typeof ShopSettingsRoute
  ShopStaffRoute: typeof ShopStaffRoute
  ShopUpgradeRoute: typeof ShopUpgradeRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiBillingExpireSweepRoute: typeof ApiBillingExpireSweepRoute
  ApiBillingPlanCheckoutRoute: typeof ApiBillingPlanCheckoutRoute
  ApiBillingPlanConfirmRoute: typeof ApiBillingPlanConfirmRoute
  ApiMollieWebhookRoute: typeof ApiMollieWebhookRoute
  BeheerAdLoginRoute: typeof BeheerAdLoginRoute
  BeheerDashboardBillingRoute: typeof BeheerDashboardBillingRoute
  BeheerDashboardBookingsRoute: typeof BeheerDashboardBookingsRoute
  BeheerDashboardDemoRoute: typeof BeheerDashboardDemoRoute
  BeheerDashboardLogsRoute: typeof BeheerDashboardLogsRoute
  BeheerDashboardMessagesRoute: typeof BeheerDashboardMessagesRoute
  BeheerDashboardPaymentsRoute: typeof BeheerDashboardPaymentsRoute
  BeheerDashboardPlansRoute: typeof BeheerDashboardPlansRoute
  BeheerDashboardProvidersRoute: typeof BeheerDashboardProvidersRoute
  BeheerDashboardSettingsRoute: typeof BeheerDashboardSettingsRoute
  BeheerDashboardShopsRoute: typeof BeheerDashboardShopsRoute
  BeheerDashboardSupportRoute: typeof BeheerDashboardSupportRoute
  BeheerDashboardUsersRoute: typeof BeheerDashboardUsersRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  BeheerDashboardIndexRoute: typeof BeheerDashboardIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/upgrade': {
      id: '/shop/upgrade'
      path: '/shop/upgrade'
      fullPath: '/shop/upgrade'
      preLoaderRoute: typeof ShopUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/staff': {
      id: '/shop/staff'
      path: '/shop/staff'
      fullPath: '/shop/staff'
      preLoaderRoute: typeof ShopStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/settings': {
      id: '/shop/settings'
      path: '/shop/settings'
      fullPath: '/shop/settings'
      preLoaderRoute: typeof ShopSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/services': {
      id: '/shop/services'
      path: '/shop/services'
      fullPath: '/shop/services'
      preLoaderRoute: typeof ShopServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/payments': {
      id: '/shop/payments'
      path: '/shop/payments'
      fullPath: '/shop/payments'
      preLoaderRoute: typeof ShopPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/notifications': {
      id: '/shop/notifications'
      path: '/shop/notifications'
      fullPath: '/shop/notifications'
      preLoaderRoute: typeof ShopNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/customers': {
      id: '/shop/customers'
      path: '/shop/customers'
      fullPath: '/shop/customers'
      preLoaderRoute: typeof ShopCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/calendar': {
      id: '/shop/calendar'
      path: '/shop/calendar'
      fullPath: '/shop/calendar'
      preLoaderRoute: typeof ShopCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/billing': {
      id: '/shop/billing'
      path: '/shop/billing'
      fullPath: '/shop/billing'
      preLoaderRoute: typeof ShopBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/analytics': {
      id: '/shop/analytics'
      path: '/shop/analytics'
      fullPath: '/shop/analytics'
      preLoaderRoute: typeof ShopAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/booking-confirmation': {
      id: '/hooks/booking-confirmation'
      path: '/hooks/booking-confirmation'
      fullPath: '/hooks/booking-confirmation'
      preLoaderRoute: typeof HooksBookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/booking-automations': {
      id: '/hooks/booking-automations'
      path: '/hooks/booking-automations'
      fullPath: '/hooks/booking-automations'
      preLoaderRoute: typeof HooksBookingAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/': {
      id: '/beheer/dashboard/'
      path: '/beheer/dashboard'
      fullPath: '/beheer/dashboard/'
      preLoaderRoute: typeof BeheerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/customers/$customerId': {
      id: '/shop/customers/$customerId'
      path: '/$customerId'
      fullPath: '/shop/customers/$customerId'
      preLoaderRoute: typeof ShopCustomersCustomerIdRouteImport
      parentRoute: typeof ShopCustomersRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmation/$bookingId': {
      id: '/book/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/book/confirmation/$bookingId'
      preLoaderRoute: typeof BookConfirmationBookingIdRouteImport
      parentRoute: typeof BookRoute
    }
    '/beheer/dashboard/users': {
      id: '/beheer/dashboard/users'
      path: '/beheer/dashboard/users'
      fullPath: '/beheer/dashboard/users'
      preLoaderRoute: typeof BeheerDashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/support': {
      id: '/beheer/dashboard/support'
      path: '/beheer/dashboard/support'
      fullPath: '/beheer/dashboard/support'
      preLoaderRoute: typeof BeheerDashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/shops': {
      id: '/beheer/dashboard/shops'
      path: '/beheer/dashboard/shops'
      fullPath: '/beheer/dashboard/shops'
      preLoaderRoute: typeof BeheerDashboardShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/settings': {
      id: '/beheer/dashboard/settings'
      path: '/beheer/dashboard/settings'
      fullPath: '/beheer/dashboard/settings'
      preLoaderRoute: typeof BeheerDashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/providers': {
      id: '/beheer/dashboard/providers'
      path: '/beheer/dashboard/providers'
      fullPath: '/beheer/dashboard/providers'
      preLoaderRoute: typeof BeheerDashboardProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/plans': {
      id: '/beheer/dashboard/plans'
      path: '/beheer/dashboard/plans'
      fullPath: '/beheer/dashboard/plans'
      preLoaderRoute: typeof BeheerDashboardPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/payments': {
      id: '/beheer/dashboard/payments'
      path: '/beheer/dashboard/payments'
      fullPath: '/beheer/dashboard/payments'
      preLoaderRoute: typeof BeheerDashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/messages': {
      id: '/beheer/dashboard/messages'
      path: '/beheer/dashboard/messages'
      fullPath: '/beheer/dashboard/messages'
      preLoaderRoute: typeof BeheerDashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/logs': {
      id: '/beheer/dashboard/logs'
      path: '/beheer/dashboard/logs'
      fullPath: '/beheer/dashboard/logs'
      preLoaderRoute: typeof BeheerDashboardLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/demo': {
      id: '/beheer/dashboard/demo'
      path: '/beheer/dashboard/demo'
      fullPath: '/beheer/dashboard/demo'
      preLoaderRoute: typeof BeheerDashboardDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/bookings': {
      id: '/beheer/dashboard/bookings'
      path: '/beheer/dashboard/bookings'
      fullPath: '/beheer/dashboard/bookings'
      preLoaderRoute: typeof BeheerDashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/billing': {
      id: '/beheer/dashboard/billing'
      path: '/beheer/dashboard/billing'
      fullPath: '/beheer/dashboard/billing'
      preLoaderRoute: typeof BeheerDashboardBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/ad/login': {
      id: '/beheer/ad/login'
      path: '/beheer/ad/login'
      fullPath: '/beheer/ad/login'
      preLoaderRoute: typeof BeheerAdLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie/webhook': {
      id: '/api/mollie/webhook'
      path: '/api/mollie/webhook'
      fullPath: '/api/mollie/webhook'
      preLoaderRoute: typeof ApiMollieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plan-confirm': {
      id: '/api/billing/plan-confirm'
      path: '/api/billing/plan-confirm'
      fullPath: '/api/billing/plan-confirm'
      preLoaderRoute: typeof ApiBillingPlanConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plan-checkout': {
      id: '/api/billing/plan-checkout'
      path: '/api/billing/plan-checkout'
      fullPath: '/api/billing/plan-checkout'
      preLoaderRoute: typeof ApiBillingPlanCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/expire-sweep': {
      id: '/api/billing/expire-sweep'
      path: '/api/billing/expire-sweep'
      fullPath: '/api/billing/expire-sweep'
      preLoaderRoute: typeof ApiBillingExpireSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookConfirmationBookingIdRoute: typeof BookConfirmationBookingIdRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookConfirmationBookingIdRoute: BookConfirmationBookingIdRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface ShopCustomersRouteChildren {
  ShopCustomersCustomerIdRoute: typeof ShopCustomersCustomerIdRoute
}

const ShopCustomersRouteChildren: ShopCustomersRouteChildren = {
  ShopCustomersCustomerIdRoute: ShopCustomersCustomerIdRoute,
}

const ShopCustomersRouteWithChildren = ShopCustomersRoute._addFileChildren(
  ShopCustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  HooksBookingAutomationsRoute: HooksBookingAutomationsRoute,
  HooksBookingConfirmationRoute: HooksBookingConfirmationRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  ShopAnalyticsRoute: ShopAnalyticsRoute,
  ShopBillingRoute: ShopBillingRoute,
  ShopCalendarRoute: ShopCalendarRoute,
  ShopCustomersRoute: ShopCustomersRouteWithChildren,
  ShopNotificationsRoute: ShopNotificationsRoute,
  ShopPaymentsRoute: ShopPaymentsRoute,
  ShopServicesRoute: ShopServicesRoute,
  ShopSettingsRoute: ShopSettingsRoute,
  ShopStaffRoute: ShopStaffRoute,
  ShopUpgradeRoute: ShopUpgradeRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiBillingExpireSweepRoute: ApiBillingExpireSweepRoute,
  ApiBillingPlanCheckoutRoute: ApiBillingPlanCheckoutRoute,
  ApiBillingPlanConfirmRoute: ApiBillingPlanConfirmRoute,
  ApiMollieWebhookRoute: ApiMollieWebhookRoute,
  BeheerAdLoginRoute: BeheerAdLoginRoute,
  BeheerDashboardBillingRoute: BeheerDashboardBillingRoute,
  BeheerDashboardBookingsRoute: BeheerDashboardBookingsRoute,
  BeheerDashboardDemoRoute: BeheerDashboardDemoRoute,
  BeheerDashboardLogsRoute: BeheerDashboardLogsRoute,
  BeheerDashboardMessagesRoute: BeheerDashboardMessagesRoute,
  BeheerDashboardPaymentsRoute: BeheerDashboardPaymentsRoute,
  BeheerDashboardPlansRoute: BeheerDashboardPlansRoute,
  BeheerDashboardProvidersRoute: BeheerDashboardProvidersRoute,
  BeheerDashboardSettingsRoute: BeheerDashboardSettingsRoute,
  BeheerDashboardShopsRoute: BeheerDashboardShopsRoute,
  BeheerDashboardSupportRoute: BeheerDashboardSupportRoute,
  BeheerDashboardUsersRoute: BeheerDashboardUsersRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  BeheerDashboardIndexRoute: BeheerDashboardIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
