/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as ShopUpgradeRouteImport } from './routes/shop.upgrade'
import { Route as ShopStaffRouteImport } from './routes/shop.staff'
import { Route as ShopSettingsRouteImport } from './routes/shop.settings'
import { Route as ShopServicesRouteImport } from './routes/shop.services'
import { Route as ShopPaymentsRouteImport } from './routes/shop.payments'
import { Route as ShopOnboardingRouteImport } from './routes/shop.onboarding'
import { Route as ShopNotificationsRouteImport } from './routes/shop.notifications'
import { Route as ShopCustomersRouteImport } from './routes/shop.customers'
import { Route as ShopCalendarRouteImport } from './routes/shop.calendar'
import { Route as ShopBillingRouteImport } from './routes/shop.billing'
import { Route as ShopAnalyticsRouteImport } from './routes/shop.analytics'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as HooksWelcomeShopOwnerRouteImport } from './routes/hooks/welcome-shop-owner'
import { Route as HooksTrialRemindersRouteImport } from './routes/hooks/trial-reminders'
import { Route as HooksSmsLowBalanceCheckRouteImport } from './routes/hooks/sms-low-balance-check'
import { Route as HooksMollieRefreshTokensRouteImport } from './routes/hooks/mollie-refresh-tokens'
import { Route as HooksExpireCancelledSubscriptionsRouteImport } from './routes/hooks/expire-cancelled-subscriptions'
import { Route as HooksBookingConfirmationRouteImport } from './routes/hooks/booking-confirmation'
import { Route as HooksBookingAutomationsRouteImport } from './routes/hooks/booking-automations'
import { Route as HooksBillingReconcileRouteImport } from './routes/hooks/billing-reconcile'
import { Route as HooksBillingExpiryRouteImport } from './routes/hooks/billing-expiry'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as BeheerDashboardIndexRouteImport } from './routes/beheer.dashboard.index'
import { Route as ShopCustomersCustomerIdRouteImport } from './routes/shop.customers.$customerId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as BookConfirmationBookingIdRouteImport } from './routes/book.confirmation.$bookingId'
import { Route as BeheerDashboardUsersRouteImport } from './routes/beheer.dashboard.users'
import { Route as BeheerDashboardSupportRouteImport } from './routes/beheer.dashboard.support'
import { Route as BeheerDashboardSmsRouteImport } from './routes/beheer.dashboard.sms'
import { Route as BeheerDashboardShopsRouteImport } from './routes/beheer.dashboard.shops'
import { Route as BeheerDashboardSettingsRouteImport } from './routes/beheer.dashboard.settings'
import { Route as BeheerDashboardSecurityRouteImport } from './routes/beheer.dashboard.security'
import { Route as BeheerDashboardRevenueRouteImport } from './routes/beheer.dashboard.revenue'
import { Route as BeheerDashboardProvidersRouteImport } from './routes/beheer.dashboard.providers'
import { Route as BeheerDashboardPlansRouteImport } from './routes/beheer.dashboard.plans'
import { Route as BeheerDashboardPaymentsRouteImport } from './routes/beheer.dashboard.payments'
import { Route as BeheerDashboardMessagesRouteImport } from './routes/beheer.dashboard.messages'
import { Route as BeheerDashboardLogsRouteImport } from './routes/beheer.dashboard.logs'
import { Route as BeheerDashboardDemoRouteImport } from './routes/beheer.dashboard.demo'
import { Route as BeheerDashboardCustomersRouteImport } from './routes/beheer.dashboard.customers'
import { Route as BeheerDashboardBookingsRouteImport } from './routes/beheer.dashboard.bookings'
import { Route as BeheerDashboardBillingRouteImport } from './routes/beheer.dashboard.billing'
import { Route as BeheerDashboardActivityRouteImport } from './routes/beheer.dashboard.activity'
import { Route as BeheerAdLoginRouteImport } from './routes/beheer.ad.login'
import { Route as ApiSmsCreditsCheckoutRouteImport } from './routes/api.sms-credits.checkout'
import { Route as ApiOgBookingRouteImport } from './routes/api.og.booking'
import { Route as ApiOgBookRouteImport } from './routes/api.og.book'
import { Route as ApiMollieWebhookRouteImport } from './routes/api.mollie.webhook'
import { Route as ApiMollieConnectWebhookRouteImport } from './routes/api.mollie-connect.webhook'
import { Route as ApiMollieConnectDisconnectRouteImport } from './routes/api.mollie-connect.disconnect'
import { Route as ApiMollieConnectCallbackRouteImport } from './routes/api.mollie-connect.callback'
import { Route as ApiMollieConnectAuthorizeRouteImport } from './routes/api.mollie-connect.authorize'
import { Route as ApiBookingsRefundRouteImport } from './routes/api.bookings.refund'
import { Route as ApiBookingsCheckoutRouteImport } from './routes/api.bookings.checkout'
import { Route as ApiBillingPlanSyncRouteImport } from './routes/api.billing.plan-sync'
import { Route as ApiBillingPlanDowngradeRouteImport } from './routes/api.billing.plan-downgrade'
import { Route as ApiBillingPlanConfirmRouteImport } from './routes/api.billing.plan-confirm'
import { Route as ApiBillingPlanCheckoutRouteImport } from './routes/api.billing.plan-checkout'
import { Route as ApiBillingPlanCancelRouteImport } from './routes/api.billing.plan-cancel'
import { Route as ApiBillingExpireSweepRouteImport } from './routes/api.billing.expire-sweep'
import { Route as ApiAdminEmailTestRouteImport } from './routes/api.admin.email-test'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as BeheerDashboardShopsShopIdRouteImport } from './routes/beheer.dashboard.shops.$shopId'
import { Route as ApiBookingBookingIdIcsRouteImport } from './routes/api.booking.$bookingId.ics'
import { Route as ApiAdminBillingPlanOverrideRouteImport } from './routes/api.admin.billing.plan-override'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const ShopUpgradeRoute = ShopUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => ShopRoute,
} as any)
const ShopStaffRoute = ShopStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSettingsRoute = ShopSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShopRoute,
} as any)
const ShopServicesRoute = ShopServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPaymentsRoute = ShopPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOnboardingRoute = ShopOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ShopRoute,
} as any)
const ShopNotificationsRoute = ShopNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCustomersRoute = ShopCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCalendarRoute = ShopCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBillingRoute = ShopBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAnalyticsRoute = ShopAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShopRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksWelcomeShopOwnerRoute = HooksWelcomeShopOwnerRouteImport.update({
  id: '/hooks/welcome-shop-owner',
  path: '/hooks/welcome-shop-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksTrialRemindersRoute = HooksTrialRemindersRouteImport.update({
  id: '/hooks/trial-reminders',
  path: '/hooks/trial-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksSmsLowBalanceCheckRoute = HooksSmsLowBalanceCheckRouteImport.update({
  id: '/hooks/sms-low-balance-check',
  path: '/hooks/sms-low-balance-check',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksMollieRefreshTokensRoute =
  HooksMollieRefreshTokensRouteImport.update({
    id: '/hooks/mollie-refresh-tokens',
    path: '/hooks/mollie-refresh-tokens',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksExpireCancelledSubscriptionsRoute =
  HooksExpireCancelledSubscriptionsRouteImport.update({
    id: '/hooks/expire-cancelled-subscriptions',
    path: '/hooks/expire-cancelled-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksBookingConfirmationRoute =
  HooksBookingConfirmationRouteImport.update({
    id: '/hooks/booking-confirmation',
    path: '/hooks/booking-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksBookingAutomationsRoute = HooksBookingAutomationsRouteImport.update({
  id: '/hooks/booking-automations',
  path: '/hooks/booking-automations',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksBillingReconcileRoute = HooksBillingReconcileRouteImport.update({
  id: '/hooks/billing-reconcile',
  path: '/hooks/billing-reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksBillingExpiryRoute = HooksBillingExpiryRouteImport.update({
  id: '/hooks/billing-expiry',
  path: '/hooks/billing-expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BookRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardIndexRoute = BeheerDashboardIndexRouteImport.update({
  id: '/beheer/dashboard/',
  path: '/beheer/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCustomersCustomerIdRoute = ShopCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => ShopCustomersRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmationBookingIdRoute =
  BookConfirmationBookingIdRouteImport.update({
    id: '/confirmation/$bookingId',
    path: '/confirmation/$bookingId',
    getParentRoute: () => BookRoute,
  } as any)
const BeheerDashboardUsersRoute = BeheerDashboardUsersRouteImport.update({
  id: '/beheer/dashboard/users',
  path: '/beheer/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardSupportRoute = BeheerDashboardSupportRouteImport.update({
  id: '/beheer/dashboard/support',
  path: '/beheer/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardSmsRoute = BeheerDashboardSmsRouteImport.update({
  id: '/beheer/dashboard/sms',
  path: '/beheer/dashboard/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardShopsRoute = BeheerDashboardShopsRouteImport.update({
  id: '/beheer/dashboard/shops',
  path: '/beheer/dashboard/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardSettingsRoute = BeheerDashboardSettingsRouteImport.update({
  id: '/beheer/dashboard/settings',
  path: '/beheer/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardSecurityRoute = BeheerDashboardSecurityRouteImport.update({
  id: '/beheer/dashboard/security',
  path: '/beheer/dashboard/security',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardRevenueRoute = BeheerDashboardRevenueRouteImport.update({
  id: '/beheer/dashboard/revenue',
  path: '/beheer/dashboard/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardProvidersRoute =
  BeheerDashboardProvidersRouteImport.update({
    id: '/beheer/dashboard/providers',
    path: '/beheer/dashboard/providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const BeheerDashboardPlansRoute = BeheerDashboardPlansRouteImport.update({
  id: '/beheer/dashboard/plans',
  path: '/beheer/dashboard/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardPaymentsRoute = BeheerDashboardPaymentsRouteImport.update({
  id: '/beheer/dashboard/payments',
  path: '/beheer/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardMessagesRoute = BeheerDashboardMessagesRouteImport.update({
  id: '/beheer/dashboard/messages',
  path: '/beheer/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardLogsRoute = BeheerDashboardLogsRouteImport.update({
  id: '/beheer/dashboard/logs',
  path: '/beheer/dashboard/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardDemoRoute = BeheerDashboardDemoRouteImport.update({
  id: '/beheer/dashboard/demo',
  path: '/beheer/dashboard/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardCustomersRoute =
  BeheerDashboardCustomersRouteImport.update({
    id: '/beheer/dashboard/customers',
    path: '/beheer/dashboard/customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const BeheerDashboardBookingsRoute = BeheerDashboardBookingsRouteImport.update({
  id: '/beheer/dashboard/bookings',
  path: '/beheer/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardBillingRoute = BeheerDashboardBillingRouteImport.update({
  id: '/beheer/dashboard/billing',
  path: '/beheer/dashboard/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardActivityRoute = BeheerDashboardActivityRouteImport.update({
  id: '/beheer/dashboard/activity',
  path: '/beheer/dashboard/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerAdLoginRoute = BeheerAdLoginRouteImport.update({
  id: '/beheer/ad/login',
  path: '/beheer/ad/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsCreditsCheckoutRoute = ApiSmsCreditsCheckoutRouteImport.update({
  id: '/api/sms-credits/checkout',
  path: '/api/sms-credits/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgBookingRoute = ApiOgBookingRouteImport.update({
  id: '/api/og/booking',
  path: '/api/og/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgBookRoute = ApiOgBookRouteImport.update({
  id: '/api/og/book',
  path: '/api/og/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMollieWebhookRoute = ApiMollieWebhookRouteImport.update({
  id: '/api/mollie/webhook',
  path: '/api/mollie/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMollieConnectWebhookRoute = ApiMollieConnectWebhookRouteImport.update({
  id: '/api/mollie-connect/webhook',
  path: '/api/mollie-connect/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMollieConnectDisconnectRoute =
  ApiMollieConnectDisconnectRouteImport.update({
    id: '/api/mollie-connect/disconnect',
    path: '/api/mollie-connect/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMollieConnectCallbackRoute =
  ApiMollieConnectCallbackRouteImport.update({
    id: '/api/mollie-connect/callback',
    path: '/api/mollie-connect/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMollieConnectAuthorizeRoute =
  ApiMollieConnectAuthorizeRouteImport.update({
    id: '/api/mollie-connect/authorize',
    path: '/api/mollie-connect/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBookingsRefundRoute = ApiBookingsRefundRouteImport.update({
  id: '/api/bookings/refund',
  path: '/api/bookings/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsCheckoutRoute = ApiBookingsCheckoutRouteImport.update({
  id: '/api/bookings/checkout',
  path: '/api/bookings/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlanSyncRoute = ApiBillingPlanSyncRouteImport.update({
  id: '/api/billing/plan-sync',
  path: '/api/billing/plan-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlanDowngradeRoute = ApiBillingPlanDowngradeRouteImport.update({
  id: '/api/billing/plan-downgrade',
  path: '/api/billing/plan-downgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlanConfirmRoute = ApiBillingPlanConfirmRouteImport.update({
  id: '/api/billing/plan-confirm',
  path: '/api/billing/plan-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlanCheckoutRoute = ApiBillingPlanCheckoutRouteImport.update({
  id: '/api/billing/plan-checkout',
  path: '/api/billing/plan-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlanCancelRoute = ApiBillingPlanCancelRouteImport.update({
  id: '/api/billing/plan-cancel',
  path: '/api/billing/plan-cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingExpireSweepRoute = ApiBillingExpireSweepRouteImport.update({
  id: '/api/billing/expire-sweep',
  path: '/api/billing/expire-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailTestRoute = ApiAdminEmailTestRouteImport.update({
  id: '/api/admin/email-test',
  path: '/api/admin/email-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardShopsShopIdRoute =
  BeheerDashboardShopsShopIdRouteImport.update({
    id: '/$shopId',
    path: '/$shopId',
    getParentRoute: () => BeheerDashboardShopsRoute,
  } as any)
const ApiBookingBookingIdIcsRoute = ApiBookingBookingIdIcsRouteImport.update({
  id: '/api/booking/$bookingId/ics',
  path: '/api/booking/$bookingId/ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBillingPlanOverrideRoute =
  ApiAdminBillingPlanOverrideRouteImport.update({
    id: '/api/admin/billing/plan-override',
    path: '/api/admin/billing/plan-override',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/billing-expiry': typeof HooksBillingExpiryRoute
  '/hooks/billing-reconcile': typeof HooksBillingReconcileRoute
  '/hooks/booking-automations': typeof HooksBookingAutomationsRoute
  '/hooks/booking-confirmation': typeof HooksBookingConfirmationRoute
  '/hooks/expire-cancelled-subscriptions': typeof HooksExpireCancelledSubscriptionsRoute
  '/hooks/mollie-refresh-tokens': typeof HooksMollieRefreshTokensRoute
  '/hooks/sms-low-balance-check': typeof HooksSmsLowBalanceCheckRoute
  '/hooks/trial-reminders': typeof HooksTrialRemindersRoute
  '/hooks/welcome-shop-owner': typeof HooksWelcomeShopOwnerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/billing': typeof ShopBillingRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRouteWithChildren
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/onboarding': typeof ShopOnboardingRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop/upgrade': typeof ShopUpgradeRoute
  '/book/': typeof BookIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/admin/email-test': typeof ApiAdminEmailTestRoute
  '/api/billing/expire-sweep': typeof ApiBillingExpireSweepRoute
  '/api/billing/plan-cancel': typeof ApiBillingPlanCancelRoute
  '/api/billing/plan-checkout': typeof ApiBillingPlanCheckoutRoute
  '/api/billing/plan-confirm': typeof ApiBillingPlanConfirmRoute
  '/api/billing/plan-downgrade': typeof ApiBillingPlanDowngradeRoute
  '/api/billing/plan-sync': typeof ApiBillingPlanSyncRoute
  '/api/bookings/checkout': typeof ApiBookingsCheckoutRoute
  '/api/bookings/refund': typeof ApiBookingsRefundRoute
  '/api/mollie-connect/authorize': typeof ApiMollieConnectAuthorizeRoute
  '/api/mollie-connect/callback': typeof ApiMollieConnectCallbackRoute
  '/api/mollie-connect/disconnect': typeof ApiMollieConnectDisconnectRoute
  '/api/mollie-connect/webhook': typeof ApiMollieConnectWebhookRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/api/og/book': typeof ApiOgBookRoute
  '/api/og/booking': typeof ApiOgBookingRoute
  '/api/sms-credits/checkout': typeof ApiSmsCreditsCheckoutRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/activity': typeof BeheerDashboardActivityRoute
  '/beheer/dashboard/billing': typeof BeheerDashboardBillingRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/customers': typeof BeheerDashboardCustomersRoute
  '/beheer/dashboard/demo': typeof BeheerDashboardDemoRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/messages': typeof BeheerDashboardMessagesRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/providers': typeof BeheerDashboardProvidersRoute
  '/beheer/dashboard/revenue': typeof BeheerDashboardRevenueRoute
  '/beheer/dashboard/security': typeof BeheerDashboardSecurityRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRouteWithChildren
  '/beheer/dashboard/sms': typeof BeheerDashboardSmsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/customers/$customerId': typeof ShopCustomersCustomerIdRoute
  '/beheer/dashboard/': typeof BeheerDashboardIndexRoute
  '/api/admin/billing/plan-override': typeof ApiAdminBillingPlanOverrideRoute
  '/api/booking/$bookingId/ics': typeof ApiBookingBookingIdIcsRoute
  '/beheer/dashboard/shops/$shopId': typeof BeheerDashboardShopsShopIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/billing-expiry': typeof HooksBillingExpiryRoute
  '/hooks/billing-reconcile': typeof HooksBillingReconcileRoute
  '/hooks/booking-automations': typeof HooksBookingAutomationsRoute
  '/hooks/booking-confirmation': typeof HooksBookingConfirmationRoute
  '/hooks/expire-cancelled-subscriptions': typeof HooksExpireCancelledSubscriptionsRoute
  '/hooks/mollie-refresh-tokens': typeof HooksMollieRefreshTokensRoute
  '/hooks/sms-low-balance-check': typeof HooksSmsLowBalanceCheckRoute
  '/hooks/trial-reminders': typeof HooksTrialRemindersRoute
  '/hooks/welcome-shop-owner': typeof HooksWelcomeShopOwnerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/billing': typeof ShopBillingRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRouteWithChildren
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/onboarding': typeof ShopOnboardingRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop/upgrade': typeof ShopUpgradeRoute
  '/book': typeof BookIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/admin/email-test': typeof ApiAdminEmailTestRoute
  '/api/billing/expire-sweep': typeof ApiBillingExpireSweepRoute
  '/api/billing/plan-cancel': typeof ApiBillingPlanCancelRoute
  '/api/billing/plan-checkout': typeof ApiBillingPlanCheckoutRoute
  '/api/billing/plan-confirm': typeof ApiBillingPlanConfirmRoute
  '/api/billing/plan-downgrade': typeof ApiBillingPlanDowngradeRoute
  '/api/billing/plan-sync': typeof ApiBillingPlanSyncRoute
  '/api/bookings/checkout': typeof ApiBookingsCheckoutRoute
  '/api/bookings/refund': typeof ApiBookingsRefundRoute
  '/api/mollie-connect/authorize': typeof ApiMollieConnectAuthorizeRoute
  '/api/mollie-connect/callback': typeof ApiMollieConnectCallbackRoute
  '/api/mollie-connect/disconnect': typeof ApiMollieConnectDisconnectRoute
  '/api/mollie-connect/webhook': typeof ApiMollieConnectWebhookRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/api/og/book': typeof ApiOgBookRoute
  '/api/og/booking': typeof ApiOgBookingRoute
  '/api/sms-credits/checkout': typeof ApiSmsCreditsCheckoutRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/activity': typeof BeheerDashboardActivityRoute
  '/beheer/dashboard/billing': typeof BeheerDashboardBillingRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/customers': typeof BeheerDashboardCustomersRoute
  '/beheer/dashboard/demo': typeof BeheerDashboardDemoRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/messages': typeof BeheerDashboardMessagesRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/providers': typeof BeheerDashboardProvidersRoute
  '/beheer/dashboard/revenue': typeof BeheerDashboardRevenueRoute
  '/beheer/dashboard/security': typeof BeheerDashboardSecurityRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRouteWithChildren
  '/beheer/dashboard/sms': typeof BeheerDashboardSmsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/customers/$customerId': typeof ShopCustomersCustomerIdRoute
  '/beheer/dashboard': typeof BeheerDashboardIndexRoute
  '/api/admin/billing/plan-override': typeof ApiAdminBillingPlanOverrideRoute
  '/api/booking/$bookingId/ics': typeof ApiBookingBookingIdIcsRoute
  '/beheer/dashboard/shops/$shopId': typeof BeheerDashboardShopsShopIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/book/$slug': typeof BookSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/billing-expiry': typeof HooksBillingExpiryRoute
  '/hooks/billing-reconcile': typeof HooksBillingReconcileRoute
  '/hooks/booking-automations': typeof HooksBookingAutomationsRoute
  '/hooks/booking-confirmation': typeof HooksBookingConfirmationRoute
  '/hooks/expire-cancelled-subscriptions': typeof HooksExpireCancelledSubscriptionsRoute
  '/hooks/mollie-refresh-tokens': typeof HooksMollieRefreshTokensRoute
  '/hooks/sms-low-balance-check': typeof HooksSmsLowBalanceCheckRoute
  '/hooks/trial-reminders': typeof HooksTrialRemindersRoute
  '/hooks/welcome-shop-owner': typeof HooksWelcomeShopOwnerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/billing': typeof ShopBillingRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRouteWithChildren
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/onboarding': typeof ShopOnboardingRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop/upgrade': typeof ShopUpgradeRoute
  '/book/': typeof BookIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/admin/email-test': typeof ApiAdminEmailTestRoute
  '/api/billing/expire-sweep': typeof ApiBillingExpireSweepRoute
  '/api/billing/plan-cancel': typeof ApiBillingPlanCancelRoute
  '/api/billing/plan-checkout': typeof ApiBillingPlanCheckoutRoute
  '/api/billing/plan-confirm': typeof ApiBillingPlanConfirmRoute
  '/api/billing/plan-downgrade': typeof ApiBillingPlanDowngradeRoute
  '/api/billing/plan-sync': typeof ApiBillingPlanSyncRoute
  '/api/bookings/checkout': typeof ApiBookingsCheckoutRoute
  '/api/bookings/refund': typeof ApiBookingsRefundRoute
  '/api/mollie-connect/authorize': typeof ApiMollieConnectAuthorizeRoute
  '/api/mollie-connect/callback': typeof ApiMollieConnectCallbackRoute
  '/api/mollie-connect/disconnect': typeof ApiMollieConnectDisconnectRoute
  '/api/mollie-connect/webhook': typeof ApiMollieConnectWebhookRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/api/og/book': typeof ApiOgBookRoute
  '/api/og/booking': typeof ApiOgBookingRoute
  '/api/sms-credits/checkout': typeof ApiSmsCreditsCheckoutRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/activity': typeof BeheerDashboardActivityRoute
  '/beheer/dashboard/billing': typeof BeheerDashboardBillingRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/customers': typeof BeheerDashboardCustomersRoute
  '/beheer/dashboard/demo': typeof BeheerDashboardDemoRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/messages': typeof BeheerDashboardMessagesRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/providers': typeof BeheerDashboardProvidersRoute
  '/beheer/dashboard/revenue': typeof BeheerDashboardRevenueRoute
  '/beheer/dashboard/security': typeof BeheerDashboardSecurityRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRouteWithChildren
  '/beheer/dashboard/sms': typeof BeheerDashboardSmsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/shop/customers/$customerId': typeof ShopCustomersCustomerIdRoute
  '/beheer/dashboard/': typeof BeheerDashboardIndexRoute
  '/api/admin/billing/plan-override': typeof ApiAdminBillingPlanOverrideRoute
  '/api/booking/$bookingId/ics': typeof ApiBookingBookingIdIcsRoute
  '/beheer/dashboard/shops/$shopId': typeof BeheerDashboardShopsShopIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/demo'
    | '/login'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/hooks/billing-expiry'
    | '/hooks/billing-reconcile'
    | '/hooks/booking-automations'
    | '/hooks/booking-confirmation'
    | '/hooks/expire-cancelled-subscriptions'
    | '/hooks/mollie-refresh-tokens'
    | '/hooks/sms-low-balance-check'
    | '/hooks/trial-reminders'
    | '/hooks/welcome-shop-owner'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/shop/analytics'
    | '/shop/billing'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/onboarding'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop/upgrade'
    | '/book/'
    | '/shop/'
    | '/api/admin/email-test'
    | '/api/billing/expire-sweep'
    | '/api/billing/plan-cancel'
    | '/api/billing/plan-checkout'
    | '/api/billing/plan-confirm'
    | '/api/billing/plan-downgrade'
    | '/api/billing/plan-sync'
    | '/api/bookings/checkout'
    | '/api/bookings/refund'
    | '/api/mollie-connect/authorize'
    | '/api/mollie-connect/callback'
    | '/api/mollie-connect/disconnect'
    | '/api/mollie-connect/webhook'
    | '/api/mollie/webhook'
    | '/api/og/book'
    | '/api/og/booking'
    | '/api/sms-credits/checkout'
    | '/beheer/ad/login'
    | '/beheer/dashboard/activity'
    | '/beheer/dashboard/billing'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/customers'
    | '/beheer/dashboard/demo'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/messages'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/providers'
    | '/beheer/dashboard/revenue'
    | '/beheer/dashboard/security'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/sms'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/lovable/email/suppression'
    | '/shop/customers/$customerId'
    | '/beheer/dashboard/'
    | '/api/admin/billing/plan-override'
    | '/api/booking/$bookingId/ics'
    | '/beheer/dashboard/shops/$shopId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/hooks/billing-expiry'
    | '/hooks/billing-reconcile'
    | '/hooks/booking-automations'
    | '/hooks/booking-confirmation'
    | '/hooks/expire-cancelled-subscriptions'
    | '/hooks/mollie-refresh-tokens'
    | '/hooks/sms-low-balance-check'
    | '/hooks/trial-reminders'
    | '/hooks/welcome-shop-owner'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/shop/analytics'
    | '/shop/billing'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/onboarding'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop/upgrade'
    | '/book'
    | '/shop'
    | '/api/admin/email-test'
    | '/api/billing/expire-sweep'
    | '/api/billing/plan-cancel'
    | '/api/billing/plan-checkout'
    | '/api/billing/plan-confirm'
    | '/api/billing/plan-downgrade'
    | '/api/billing/plan-sync'
    | '/api/bookings/checkout'
    | '/api/bookings/refund'
    | '/api/mollie-connect/authorize'
    | '/api/mollie-connect/callback'
    | '/api/mollie-connect/disconnect'
    | '/api/mollie-connect/webhook'
    | '/api/mollie/webhook'
    | '/api/og/book'
    | '/api/og/booking'
    | '/api/sms-credits/checkout'
    | '/beheer/ad/login'
    | '/beheer/dashboard/activity'
    | '/beheer/dashboard/billing'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/customers'
    | '/beheer/dashboard/demo'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/messages'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/providers'
    | '/beheer/dashboard/revenue'
    | '/beheer/dashboard/security'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/sms'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/lovable/email/suppression'
    | '/shop/customers/$customerId'
    | '/beheer/dashboard'
    | '/api/admin/billing/plan-override'
    | '/api/booking/$bookingId/ics'
    | '/beheer/dashboard/shops/$shopId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/demo'
    | '/login'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/book/$slug'
    | '/email/unsubscribe'
    | '/hooks/billing-expiry'
    | '/hooks/billing-reconcile'
    | '/hooks/booking-automations'
    | '/hooks/booking-confirmation'
    | '/hooks/expire-cancelled-subscriptions'
    | '/hooks/mollie-refresh-tokens'
    | '/hooks/sms-low-balance-check'
    | '/hooks/trial-reminders'
    | '/hooks/welcome-shop-owner'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/shop/analytics'
    | '/shop/billing'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/onboarding'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop/upgrade'
    | '/book/'
    | '/shop/'
    | '/api/admin/email-test'
    | '/api/billing/expire-sweep'
    | '/api/billing/plan-cancel'
    | '/api/billing/plan-checkout'
    | '/api/billing/plan-confirm'
    | '/api/billing/plan-downgrade'
    | '/api/billing/plan-sync'
    | '/api/bookings/checkout'
    | '/api/bookings/refund'
    | '/api/mollie-connect/authorize'
    | '/api/mollie-connect/callback'
    | '/api/mollie-connect/disconnect'
    | '/api/mollie-connect/webhook'
    | '/api/mollie/webhook'
    | '/api/og/book'
    | '/api/og/booking'
    | '/api/sms-credits/checkout'
    | '/beheer/ad/login'
    | '/beheer/dashboard/activity'
    | '/beheer/dashboard/billing'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/customers'
    | '/beheer/dashboard/demo'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/messages'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/providers'
    | '/beheer/dashboard/revenue'
    | '/beheer/dashboard/security'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/sms'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/lovable/email/suppression'
    | '/shop/customers/$customerId'
    | '/beheer/dashboard/'
    | '/api/admin/billing/plan-override'
    | '/api/booking/$bookingId/ics'
    | '/beheer/dashboard/shops/$shopId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  HooksBillingExpiryRoute: typeof HooksBillingExpiryRoute
  HooksBillingReconcileRoute: typeof HooksBillingReconcileRoute
  HooksBookingAutomationsRoute: typeof HooksBookingAutomationsRoute
  HooksBookingConfirmationRoute: typeof HooksBookingConfirmationRoute
  HooksExpireCancelledSubscriptionsRoute: typeof HooksExpireCancelledSubscriptionsRoute
  HooksMollieRefreshTokensRoute: typeof HooksMollieRefreshTokensRoute
  HooksSmsLowBalanceCheckRoute: typeof HooksSmsLowBalanceCheckRoute
  HooksTrialRemindersRoute: typeof HooksTrialRemindersRoute
  HooksWelcomeShopOwnerRoute: typeof HooksWelcomeShopOwnerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAdminEmailTestRoute: typeof ApiAdminEmailTestRoute
  ApiBillingExpireSweepRoute: typeof ApiBillingExpireSweepRoute
  ApiBillingPlanCancelRoute: typeof ApiBillingPlanCancelRoute
  ApiBillingPlanCheckoutRoute: typeof ApiBillingPlanCheckoutRoute
  ApiBillingPlanConfirmRoute: typeof ApiBillingPlanConfirmRoute
  ApiBillingPlanDowngradeRoute: typeof ApiBillingPlanDowngradeRoute
  ApiBillingPlanSyncRoute: typeof ApiBillingPlanSyncRoute
  ApiBookingsCheckoutRoute: typeof ApiBookingsCheckoutRoute
  ApiBookingsRefundRoute: typeof ApiBookingsRefundRoute
  ApiMollieConnectAuthorizeRoute: typeof ApiMollieConnectAuthorizeRoute
  ApiMollieConnectCallbackRoute: typeof ApiMollieConnectCallbackRoute
  ApiMollieConnectDisconnectRoute: typeof ApiMollieConnectDisconnectRoute
  ApiMollieConnectWebhookRoute: typeof ApiMollieConnectWebhookRoute
  ApiMollieWebhookRoute: typeof ApiMollieWebhookRoute
  ApiOgBookRoute: typeof ApiOgBookRoute
  ApiOgBookingRoute: typeof ApiOgBookingRoute
  ApiSmsCreditsCheckoutRoute: typeof ApiSmsCreditsCheckoutRoute
  BeheerAdLoginRoute: typeof BeheerAdLoginRoute
  BeheerDashboardActivityRoute: typeof BeheerDashboardActivityRoute
  BeheerDashboardBillingRoute: typeof BeheerDashboardBillingRoute
  BeheerDashboardBookingsRoute: typeof BeheerDashboardBookingsRoute
  BeheerDashboardCustomersRoute: typeof BeheerDashboardCustomersRoute
  BeheerDashboardDemoRoute: typeof BeheerDashboardDemoRoute
  BeheerDashboardLogsRoute: typeof BeheerDashboardLogsRoute
  BeheerDashboardMessagesRoute: typeof BeheerDashboardMessagesRoute
  BeheerDashboardPaymentsRoute: typeof BeheerDashboardPaymentsRoute
  BeheerDashboardPlansRoute: typeof BeheerDashboardPlansRoute
  BeheerDashboardProvidersRoute: typeof BeheerDashboardProvidersRoute
  BeheerDashboardRevenueRoute: typeof BeheerDashboardRevenueRoute
  BeheerDashboardSecurityRoute: typeof BeheerDashboardSecurityRoute
  BeheerDashboardSettingsRoute: typeof BeheerDashboardSettingsRoute
  BeheerDashboardShopsRoute: typeof BeheerDashboardShopsRouteWithChildren
  BeheerDashboardSmsRoute: typeof BeheerDashboardSmsRoute
  BeheerDashboardSupportRoute: typeof BeheerDashboardSupportRoute
  BeheerDashboardUsersRoute: typeof BeheerDashboardUsersRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  BeheerDashboardIndexRoute: typeof BeheerDashboardIndexRoute
  ApiAdminBillingPlanOverrideRoute: typeof ApiAdminBillingPlanOverrideRoute
  ApiBookingBookingIdIcsRoute: typeof ApiBookingBookingIdIcsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/book/': {
      id: '/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/shop/upgrade': {
      id: '/shop/upgrade'
      path: '/upgrade'
      fullPath: '/shop/upgrade'
      preLoaderRoute: typeof ShopUpgradeRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/staff': {
      id: '/shop/staff'
      path: '/staff'
      fullPath: '/shop/staff'
      preLoaderRoute: typeof ShopStaffRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/settings': {
      id: '/shop/settings'
      path: '/settings'
      fullPath: '/shop/settings'
      preLoaderRoute: typeof ShopSettingsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/services': {
      id: '/shop/services'
      path: '/services'
      fullPath: '/shop/services'
      preLoaderRoute: typeof ShopServicesRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/payments': {
      id: '/shop/payments'
      path: '/payments'
      fullPath: '/shop/payments'
      preLoaderRoute: typeof ShopPaymentsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/onboarding': {
      id: '/shop/onboarding'
      path: '/onboarding'
      fullPath: '/shop/onboarding'
      preLoaderRoute: typeof ShopOnboardingRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/notifications': {
      id: '/shop/notifications'
      path: '/notifications'
      fullPath: '/shop/notifications'
      preLoaderRoute: typeof ShopNotificationsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/customers': {
      id: '/shop/customers'
      path: '/customers'
      fullPath: '/shop/customers'
      preLoaderRoute: typeof ShopCustomersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/calendar': {
      id: '/shop/calendar'
      path: '/calendar'
      fullPath: '/shop/calendar'
      preLoaderRoute: typeof ShopCalendarRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/billing': {
      id: '/shop/billing'
      path: '/billing'
      fullPath: '/shop/billing'
      preLoaderRoute: typeof ShopBillingRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/analytics': {
      id: '/shop/analytics'
      path: '/analytics'
      fullPath: '/shop/analytics'
      preLoaderRoute: typeof ShopAnalyticsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/welcome-shop-owner': {
      id: '/hooks/welcome-shop-owner'
      path: '/hooks/welcome-shop-owner'
      fullPath: '/hooks/welcome-shop-owner'
      preLoaderRoute: typeof HooksWelcomeShopOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/trial-reminders': {
      id: '/hooks/trial-reminders'
      path: '/hooks/trial-reminders'
      fullPath: '/hooks/trial-reminders'
      preLoaderRoute: typeof HooksTrialRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/sms-low-balance-check': {
      id: '/hooks/sms-low-balance-check'
      path: '/hooks/sms-low-balance-check'
      fullPath: '/hooks/sms-low-balance-check'
      preLoaderRoute: typeof HooksSmsLowBalanceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/mollie-refresh-tokens': {
      id: '/hooks/mollie-refresh-tokens'
      path: '/hooks/mollie-refresh-tokens'
      fullPath: '/hooks/mollie-refresh-tokens'
      preLoaderRoute: typeof HooksMollieRefreshTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/expire-cancelled-subscriptions': {
      id: '/hooks/expire-cancelled-subscriptions'
      path: '/hooks/expire-cancelled-subscriptions'
      fullPath: '/hooks/expire-cancelled-subscriptions'
      preLoaderRoute: typeof HooksExpireCancelledSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/booking-confirmation': {
      id: '/hooks/booking-confirmation'
      path: '/hooks/booking-confirmation'
      fullPath: '/hooks/booking-confirmation'
      preLoaderRoute: typeof HooksBookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/booking-automations': {
      id: '/hooks/booking-automations'
      path: '/hooks/booking-automations'
      fullPath: '/hooks/booking-automations'
      preLoaderRoute: typeof HooksBookingAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/billing-reconcile': {
      id: '/hooks/billing-reconcile'
      path: '/hooks/billing-reconcile'
      fullPath: '/hooks/billing-reconcile'
      preLoaderRoute: typeof HooksBillingReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/billing-expiry': {
      id: '/hooks/billing-expiry'
      path: '/hooks/billing-expiry'
      fullPath: '/hooks/billing-expiry'
      preLoaderRoute: typeof HooksBillingExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof BookRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/': {
      id: '/beheer/dashboard/'
      path: '/beheer/dashboard'
      fullPath: '/beheer/dashboard/'
      preLoaderRoute: typeof BeheerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/customers/$customerId': {
      id: '/shop/customers/$customerId'
      path: '/$customerId'
      fullPath: '/shop/customers/$customerId'
      preLoaderRoute: typeof ShopCustomersCustomerIdRouteImport
      parentRoute: typeof ShopCustomersRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmation/$bookingId': {
      id: '/book/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/book/confirmation/$bookingId'
      preLoaderRoute: typeof BookConfirmationBookingIdRouteImport
      parentRoute: typeof BookRoute
    }
    '/beheer/dashboard/users': {
      id: '/beheer/dashboard/users'
      path: '/beheer/dashboard/users'
      fullPath: '/beheer/dashboard/users'
      preLoaderRoute: typeof BeheerDashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/support': {
      id: '/beheer/dashboard/support'
      path: '/beheer/dashboard/support'
      fullPath: '/beheer/dashboard/support'
      preLoaderRoute: typeof BeheerDashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/sms': {
      id: '/beheer/dashboard/sms'
      path: '/beheer/dashboard/sms'
      fullPath: '/beheer/dashboard/sms'
      preLoaderRoute: typeof BeheerDashboardSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/shops': {
      id: '/beheer/dashboard/shops'
      path: '/beheer/dashboard/shops'
      fullPath: '/beheer/dashboard/shops'
      preLoaderRoute: typeof BeheerDashboardShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/settings': {
      id: '/beheer/dashboard/settings'
      path: '/beheer/dashboard/settings'
      fullPath: '/beheer/dashboard/settings'
      preLoaderRoute: typeof BeheerDashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/security': {
      id: '/beheer/dashboard/security'
      path: '/beheer/dashboard/security'
      fullPath: '/beheer/dashboard/security'
      preLoaderRoute: typeof BeheerDashboardSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/revenue': {
      id: '/beheer/dashboard/revenue'
      path: '/beheer/dashboard/revenue'
      fullPath: '/beheer/dashboard/revenue'
      preLoaderRoute: typeof BeheerDashboardRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/providers': {
      id: '/beheer/dashboard/providers'
      path: '/beheer/dashboard/providers'
      fullPath: '/beheer/dashboard/providers'
      preLoaderRoute: typeof BeheerDashboardProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/plans': {
      id: '/beheer/dashboard/plans'
      path: '/beheer/dashboard/plans'
      fullPath: '/beheer/dashboard/plans'
      preLoaderRoute: typeof BeheerDashboardPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/payments': {
      id: '/beheer/dashboard/payments'
      path: '/beheer/dashboard/payments'
      fullPath: '/beheer/dashboard/payments'
      preLoaderRoute: typeof BeheerDashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/messages': {
      id: '/beheer/dashboard/messages'
      path: '/beheer/dashboard/messages'
      fullPath: '/beheer/dashboard/messages'
      preLoaderRoute: typeof BeheerDashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/logs': {
      id: '/beheer/dashboard/logs'
      path: '/beheer/dashboard/logs'
      fullPath: '/beheer/dashboard/logs'
      preLoaderRoute: typeof BeheerDashboardLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/demo': {
      id: '/beheer/dashboard/demo'
      path: '/beheer/dashboard/demo'
      fullPath: '/beheer/dashboard/demo'
      preLoaderRoute: typeof BeheerDashboardDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/customers': {
      id: '/beheer/dashboard/customers'
      path: '/beheer/dashboard/customers'
      fullPath: '/beheer/dashboard/customers'
      preLoaderRoute: typeof BeheerDashboardCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/bookings': {
      id: '/beheer/dashboard/bookings'
      path: '/beheer/dashboard/bookings'
      fullPath: '/beheer/dashboard/bookings'
      preLoaderRoute: typeof BeheerDashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/billing': {
      id: '/beheer/dashboard/billing'
      path: '/beheer/dashboard/billing'
      fullPath: '/beheer/dashboard/billing'
      preLoaderRoute: typeof BeheerDashboardBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/activity': {
      id: '/beheer/dashboard/activity'
      path: '/beheer/dashboard/activity'
      fullPath: '/beheer/dashboard/activity'
      preLoaderRoute: typeof BeheerDashboardActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/ad/login': {
      id: '/beheer/ad/login'
      path: '/beheer/ad/login'
      fullPath: '/beheer/ad/login'
      preLoaderRoute: typeof BeheerAdLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms-credits/checkout': {
      id: '/api/sms-credits/checkout'
      path: '/api/sms-credits/checkout'
      fullPath: '/api/sms-credits/checkout'
      preLoaderRoute: typeof ApiSmsCreditsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/booking': {
      id: '/api/og/booking'
      path: '/api/og/booking'
      fullPath: '/api/og/booking'
      preLoaderRoute: typeof ApiOgBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/book': {
      id: '/api/og/book'
      path: '/api/og/book'
      fullPath: '/api/og/book'
      preLoaderRoute: typeof ApiOgBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie/webhook': {
      id: '/api/mollie/webhook'
      path: '/api/mollie/webhook'
      fullPath: '/api/mollie/webhook'
      preLoaderRoute: typeof ApiMollieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie-connect/webhook': {
      id: '/api/mollie-connect/webhook'
      path: '/api/mollie-connect/webhook'
      fullPath: '/api/mollie-connect/webhook'
      preLoaderRoute: typeof ApiMollieConnectWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie-connect/disconnect': {
      id: '/api/mollie-connect/disconnect'
      path: '/api/mollie-connect/disconnect'
      fullPath: '/api/mollie-connect/disconnect'
      preLoaderRoute: typeof ApiMollieConnectDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie-connect/callback': {
      id: '/api/mollie-connect/callback'
      path: '/api/mollie-connect/callback'
      fullPath: '/api/mollie-connect/callback'
      preLoaderRoute: typeof ApiMollieConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie-connect/authorize': {
      id: '/api/mollie-connect/authorize'
      path: '/api/mollie-connect/authorize'
      fullPath: '/api/mollie-connect/authorize'
      preLoaderRoute: typeof ApiMollieConnectAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/refund': {
      id: '/api/bookings/refund'
      path: '/api/bookings/refund'
      fullPath: '/api/bookings/refund'
      preLoaderRoute: typeof ApiBookingsRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/checkout': {
      id: '/api/bookings/checkout'
      path: '/api/bookings/checkout'
      fullPath: '/api/bookings/checkout'
      preLoaderRoute: typeof ApiBookingsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plan-sync': {
      id: '/api/billing/plan-sync'
      path: '/api/billing/plan-sync'
      fullPath: '/api/billing/plan-sync'
      preLoaderRoute: typeof ApiBillingPlanSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plan-downgrade': {
      id: '/api/billing/plan-downgrade'
      path: '/api/billing/plan-downgrade'
      fullPath: '/api/billing/plan-downgrade'
      preLoaderRoute: typeof ApiBillingPlanDowngradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plan-confirm': {
      id: '/api/billing/plan-confirm'
      path: '/api/billing/plan-confirm'
      fullPath: '/api/billing/plan-confirm'
      preLoaderRoute: typeof ApiBillingPlanConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plan-checkout': {
      id: '/api/billing/plan-checkout'
      path: '/api/billing/plan-checkout'
      fullPath: '/api/billing/plan-checkout'
      preLoaderRoute: typeof ApiBillingPlanCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plan-cancel': {
      id: '/api/billing/plan-cancel'
      path: '/api/billing/plan-cancel'
      fullPath: '/api/billing/plan-cancel'
      preLoaderRoute: typeof ApiBillingPlanCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/expire-sweep': {
      id: '/api/billing/expire-sweep'
      path: '/api/billing/expire-sweep'
      fullPath: '/api/billing/expire-sweep'
      preLoaderRoute: typeof ApiBillingExpireSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-test': {
      id: '/api/admin/email-test'
      path: '/api/admin/email-test'
      fullPath: '/api/admin/email-test'
      preLoaderRoute: typeof ApiAdminEmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/shops/$shopId': {
      id: '/beheer/dashboard/shops/$shopId'
      path: '/$shopId'
      fullPath: '/beheer/dashboard/shops/$shopId'
      preLoaderRoute: typeof BeheerDashboardShopsShopIdRouteImport
      parentRoute: typeof BeheerDashboardShopsRoute
    }
    '/api/booking/$bookingId/ics': {
      id: '/api/booking/$bookingId/ics'
      path: '/api/booking/$bookingId/ics'
      fullPath: '/api/booking/$bookingId/ics'
      preLoaderRoute: typeof ApiBookingBookingIdIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/billing/plan-override': {
      id: '/api/admin/billing/plan-override'
      path: '/api/admin/billing/plan-override'
      fullPath: '/api/admin/billing/plan-override'
      preLoaderRoute: typeof ApiAdminBillingPlanOverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookSlugRoute: typeof BookSlugRoute
  BookIndexRoute: typeof BookIndexRoute
  BookConfirmationBookingIdRoute: typeof BookConfirmationBookingIdRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookSlugRoute: BookSlugRoute,
  BookIndexRoute: BookIndexRoute,
  BookConfirmationBookingIdRoute: BookConfirmationBookingIdRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface ShopCustomersRouteChildren {
  ShopCustomersCustomerIdRoute: typeof ShopCustomersCustomerIdRoute
}

const ShopCustomersRouteChildren: ShopCustomersRouteChildren = {
  ShopCustomersCustomerIdRoute: ShopCustomersCustomerIdRoute,
}

const ShopCustomersRouteWithChildren = ShopCustomersRoute._addFileChildren(
  ShopCustomersRouteChildren,
)

interface ShopRouteChildren {
  ShopAnalyticsRoute: typeof ShopAnalyticsRoute
  ShopBillingRoute: typeof ShopBillingRoute
  ShopCalendarRoute: typeof ShopCalendarRoute
  ShopCustomersRoute: typeof ShopCustomersRouteWithChildren
  ShopNotificationsRoute: typeof ShopNotificationsRoute
  ShopOnboardingRoute: typeof ShopOnboardingRoute
  ShopPaymentsRoute: typeof ShopPaymentsRoute
  ShopServicesRoute: typeof ShopServicesRoute
  ShopSettingsRoute: typeof ShopSettingsRoute
  ShopStaffRoute: typeof ShopStaffRoute
  ShopUpgradeRoute: typeof ShopUpgradeRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAnalyticsRoute: ShopAnalyticsRoute,
  ShopBillingRoute: ShopBillingRoute,
  ShopCalendarRoute: ShopCalendarRoute,
  ShopCustomersRoute: ShopCustomersRouteWithChildren,
  ShopNotificationsRoute: ShopNotificationsRoute,
  ShopOnboardingRoute: ShopOnboardingRoute,
  ShopPaymentsRoute: ShopPaymentsRoute,
  ShopServicesRoute: ShopServicesRoute,
  ShopSettingsRoute: ShopSettingsRoute,
  ShopStaffRoute: ShopStaffRoute,
  ShopUpgradeRoute: ShopUpgradeRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface BeheerDashboardShopsRouteChildren {
  BeheerDashboardShopsShopIdRoute: typeof BeheerDashboardShopsShopIdRoute
}

const BeheerDashboardShopsRouteChildren: BeheerDashboardShopsRouteChildren = {
  BeheerDashboardShopsShopIdRoute: BeheerDashboardShopsShopIdRoute,
}

const BeheerDashboardShopsRouteWithChildren =
  BeheerDashboardShopsRoute._addFileChildren(BeheerDashboardShopsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  HooksBillingExpiryRoute: HooksBillingExpiryRoute,
  HooksBillingReconcileRoute: HooksBillingReconcileRoute,
  HooksBookingAutomationsRoute: HooksBookingAutomationsRoute,
  HooksBookingConfirmationRoute: HooksBookingConfirmationRoute,
  HooksExpireCancelledSubscriptionsRoute:
    HooksExpireCancelledSubscriptionsRoute,
  HooksMollieRefreshTokensRoute: HooksMollieRefreshTokensRoute,
  HooksSmsLowBalanceCheckRoute: HooksSmsLowBalanceCheckRoute,
  HooksTrialRemindersRoute: HooksTrialRemindersRoute,
  HooksWelcomeShopOwnerRoute: HooksWelcomeShopOwnerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAdminEmailTestRoute: ApiAdminEmailTestRoute,
  ApiBillingExpireSweepRoute: ApiBillingExpireSweepRoute,
  ApiBillingPlanCancelRoute: ApiBillingPlanCancelRoute,
  ApiBillingPlanCheckoutRoute: ApiBillingPlanCheckoutRoute,
  ApiBillingPlanConfirmRoute: ApiBillingPlanConfirmRoute,
  ApiBillingPlanDowngradeRoute: ApiBillingPlanDowngradeRoute,
  ApiBillingPlanSyncRoute: ApiBillingPlanSyncRoute,
  ApiBookingsCheckoutRoute: ApiBookingsCheckoutRoute,
  ApiBookingsRefundRoute: ApiBookingsRefundRoute,
  ApiMollieConnectAuthorizeRoute: ApiMollieConnectAuthorizeRoute,
  ApiMollieConnectCallbackRoute: ApiMollieConnectCallbackRoute,
  ApiMollieConnectDisconnectRoute: ApiMollieConnectDisconnectRoute,
  ApiMollieConnectWebhookRoute: ApiMollieConnectWebhookRoute,
  ApiMollieWebhookRoute: ApiMollieWebhookRoute,
  ApiOgBookRoute: ApiOgBookRoute,
  ApiOgBookingRoute: ApiOgBookingRoute,
  ApiSmsCreditsCheckoutRoute: ApiSmsCreditsCheckoutRoute,
  BeheerAdLoginRoute: BeheerAdLoginRoute,
  BeheerDashboardActivityRoute: BeheerDashboardActivityRoute,
  BeheerDashboardBillingRoute: BeheerDashboardBillingRoute,
  BeheerDashboardBookingsRoute: BeheerDashboardBookingsRoute,
  BeheerDashboardCustomersRoute: BeheerDashboardCustomersRoute,
  BeheerDashboardDemoRoute: BeheerDashboardDemoRoute,
  BeheerDashboardLogsRoute: BeheerDashboardLogsRoute,
  BeheerDashboardMessagesRoute: BeheerDashboardMessagesRoute,
  BeheerDashboardPaymentsRoute: BeheerDashboardPaymentsRoute,
  BeheerDashboardPlansRoute: BeheerDashboardPlansRoute,
  BeheerDashboardProvidersRoute: BeheerDashboardProvidersRoute,
  BeheerDashboardRevenueRoute: BeheerDashboardRevenueRoute,
  BeheerDashboardSecurityRoute: BeheerDashboardSecurityRoute,
  BeheerDashboardSettingsRoute: BeheerDashboardSettingsRoute,
  BeheerDashboardShopsRoute: BeheerDashboardShopsRouteWithChildren,
  BeheerDashboardSmsRoute: BeheerDashboardSmsRoute,
  BeheerDashboardSupportRoute: BeheerDashboardSupportRoute,
  BeheerDashboardUsersRoute: BeheerDashboardUsersRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  BeheerDashboardIndexRoute: BeheerDashboardIndexRoute,
  ApiAdminBillingPlanOverrideRoute: ApiAdminBillingPlanOverrideRoute,
  ApiBookingBookingIdIcsRoute: ApiBookingBookingIdIcsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
