/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopStaffRouteImport } from './routes/shop.staff'
import { Route as ShopSettingsRouteImport } from './routes/shop.settings'
import { Route as ShopServicesRouteImport } from './routes/shop.services'
import { Route as ShopPaymentsRouteImport } from './routes/shop.payments'
import { Route as ShopNotificationsRouteImport } from './routes/shop.notifications'
import { Route as ShopCustomersRouteImport } from './routes/shop.customers'
import { Route as ShopCalendarRouteImport } from './routes/shop.calendar'
import { Route as ShopAnalyticsRouteImport } from './routes/shop.analytics'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as BeheerDashboardIndexRouteImport } from './routes/beheer.dashboard.index'
import { Route as BookConfirmationBookingIdRouteImport } from './routes/book.confirmation.$bookingId'
import { Route as BeheerDashboardUsersRouteImport } from './routes/beheer.dashboard.users'
import { Route as BeheerDashboardSupportRouteImport } from './routes/beheer.dashboard.support'
import { Route as BeheerDashboardShopsRouteImport } from './routes/beheer.dashboard.shops'
import { Route as BeheerDashboardSettingsRouteImport } from './routes/beheer.dashboard.settings'
import { Route as BeheerDashboardPlansRouteImport } from './routes/beheer.dashboard.plans'
import { Route as BeheerDashboardPaymentsRouteImport } from './routes/beheer.dashboard.payments'
import { Route as BeheerDashboardLogsRouteImport } from './routes/beheer.dashboard.logs'
import { Route as BeheerDashboardBookingsRouteImport } from './routes/beheer.dashboard.bookings'
import { Route as BeheerAdLoginRouteImport } from './routes/beheer.ad.login'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopStaffRoute = ShopStaffRouteImport.update({
  id: '/shop/staff',
  path: '/shop/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSettingsRoute = ShopSettingsRouteImport.update({
  id: '/shop/settings',
  path: '/shop/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopServicesRoute = ShopServicesRouteImport.update({
  id: '/shop/services',
  path: '/shop/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPaymentsRoute = ShopPaymentsRouteImport.update({
  id: '/shop/payments',
  path: '/shop/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopNotificationsRoute = ShopNotificationsRouteImport.update({
  id: '/shop/notifications',
  path: '/shop/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCustomersRoute = ShopCustomersRouteImport.update({
  id: '/shop/customers',
  path: '/shop/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCalendarRoute = ShopCalendarRouteImport.update({
  id: '/shop/calendar',
  path: '/shop/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAnalyticsRoute = ShopAnalyticsRouteImport.update({
  id: '/shop/analytics',
  path: '/shop/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardIndexRoute = BeheerDashboardIndexRouteImport.update({
  id: '/beheer/dashboard/',
  path: '/beheer/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmationBookingIdRoute =
  BookConfirmationBookingIdRouteImport.update({
    id: '/confirmation/$bookingId',
    path: '/confirmation/$bookingId',
    getParentRoute: () => BookRoute,
  } as any)
const BeheerDashboardUsersRoute = BeheerDashboardUsersRouteImport.update({
  id: '/beheer/dashboard/users',
  path: '/beheer/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardSupportRoute = BeheerDashboardSupportRouteImport.update({
  id: '/beheer/dashboard/support',
  path: '/beheer/dashboard/support',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardShopsRoute = BeheerDashboardShopsRouteImport.update({
  id: '/beheer/dashboard/shops',
  path: '/beheer/dashboard/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardSettingsRoute = BeheerDashboardSettingsRouteImport.update({
  id: '/beheer/dashboard/settings',
  path: '/beheer/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardPlansRoute = BeheerDashboardPlansRouteImport.update({
  id: '/beheer/dashboard/plans',
  path: '/beheer/dashboard/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardPaymentsRoute = BeheerDashboardPaymentsRouteImport.update({
  id: '/beheer/dashboard/payments',
  path: '/beheer/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardLogsRoute = BeheerDashboardLogsRouteImport.update({
  id: '/beheer/dashboard/logs',
  path: '/beheer/dashboard/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerDashboardBookingsRoute = BeheerDashboardBookingsRouteImport.update({
  id: '/beheer/dashboard/bookings',
  path: '/beheer/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerAdLoginRoute = BeheerAdLoginRouteImport.update({
  id: '/beheer/ad/login',
  path: '/beheer/ad/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop/': typeof ShopIndexRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/beheer/dashboard/': typeof BeheerDashboardIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop': typeof ShopIndexRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/beheer/dashboard': typeof BeheerDashboardIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/shop/analytics': typeof ShopAnalyticsRoute
  '/shop/calendar': typeof ShopCalendarRoute
  '/shop/customers': typeof ShopCustomersRoute
  '/shop/notifications': typeof ShopNotificationsRoute
  '/shop/payments': typeof ShopPaymentsRoute
  '/shop/services': typeof ShopServicesRoute
  '/shop/settings': typeof ShopSettingsRoute
  '/shop/staff': typeof ShopStaffRoute
  '/shop/': typeof ShopIndexRoute
  '/beheer/ad/login': typeof BeheerAdLoginRoute
  '/beheer/dashboard/bookings': typeof BeheerDashboardBookingsRoute
  '/beheer/dashboard/logs': typeof BeheerDashboardLogsRoute
  '/beheer/dashboard/payments': typeof BeheerDashboardPaymentsRoute
  '/beheer/dashboard/plans': typeof BeheerDashboardPlansRoute
  '/beheer/dashboard/settings': typeof BeheerDashboardSettingsRoute
  '/beheer/dashboard/shops': typeof BeheerDashboardShopsRoute
  '/beheer/dashboard/support': typeof BeheerDashboardSupportRoute
  '/beheer/dashboard/users': typeof BeheerDashboardUsersRoute
  '/book/confirmation/$bookingId': typeof BookConfirmationBookingIdRoute
  '/beheer/dashboard/': typeof BeheerDashboardIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/login'
    | '/signup'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/shop/analytics'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop/'
    | '/beheer/ad/login'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/beheer/dashboard/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/signup'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/shop/analytics'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop'
    | '/beheer/ad/login'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/beheer/dashboard'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/login'
    | '/signup'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/shop/analytics'
    | '/shop/calendar'
    | '/shop/customers'
    | '/shop/notifications'
    | '/shop/payments'
    | '/shop/services'
    | '/shop/settings'
    | '/shop/staff'
    | '/shop/'
    | '/beheer/ad/login'
    | '/beheer/dashboard/bookings'
    | '/beheer/dashboard/logs'
    | '/beheer/dashboard/payments'
    | '/beheer/dashboard/plans'
    | '/beheer/dashboard/settings'
    | '/beheer/dashboard/shops'
    | '/beheer/dashboard/support'
    | '/beheer/dashboard/users'
    | '/book/confirmation/$bookingId'
    | '/beheer/dashboard/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ShopAnalyticsRoute: typeof ShopAnalyticsRoute
  ShopCalendarRoute: typeof ShopCalendarRoute
  ShopCustomersRoute: typeof ShopCustomersRoute
  ShopNotificationsRoute: typeof ShopNotificationsRoute
  ShopPaymentsRoute: typeof ShopPaymentsRoute
  ShopServicesRoute: typeof ShopServicesRoute
  ShopSettingsRoute: typeof ShopSettingsRoute
  ShopStaffRoute: typeof ShopStaffRoute
  ShopIndexRoute: typeof ShopIndexRoute
  BeheerAdLoginRoute: typeof BeheerAdLoginRoute
  BeheerDashboardBookingsRoute: typeof BeheerDashboardBookingsRoute
  BeheerDashboardLogsRoute: typeof BeheerDashboardLogsRoute
  BeheerDashboardPaymentsRoute: typeof BeheerDashboardPaymentsRoute
  BeheerDashboardPlansRoute: typeof BeheerDashboardPlansRoute
  BeheerDashboardSettingsRoute: typeof BeheerDashboardSettingsRoute
  BeheerDashboardShopsRoute: typeof BeheerDashboardShopsRoute
  BeheerDashboardSupportRoute: typeof BeheerDashboardSupportRoute
  BeheerDashboardUsersRoute: typeof BeheerDashboardUsersRoute
  BeheerDashboardIndexRoute: typeof BeheerDashboardIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/staff': {
      id: '/shop/staff'
      path: '/shop/staff'
      fullPath: '/shop/staff'
      preLoaderRoute: typeof ShopStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/settings': {
      id: '/shop/settings'
      path: '/shop/settings'
      fullPath: '/shop/settings'
      preLoaderRoute: typeof ShopSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/services': {
      id: '/shop/services'
      path: '/shop/services'
      fullPath: '/shop/services'
      preLoaderRoute: typeof ShopServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/payments': {
      id: '/shop/payments'
      path: '/shop/payments'
      fullPath: '/shop/payments'
      preLoaderRoute: typeof ShopPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/notifications': {
      id: '/shop/notifications'
      path: '/shop/notifications'
      fullPath: '/shop/notifications'
      preLoaderRoute: typeof ShopNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/customers': {
      id: '/shop/customers'
      path: '/shop/customers'
      fullPath: '/shop/customers'
      preLoaderRoute: typeof ShopCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/calendar': {
      id: '/shop/calendar'
      path: '/shop/calendar'
      fullPath: '/shop/calendar'
      preLoaderRoute: typeof ShopCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/analytics': {
      id: '/shop/analytics'
      path: '/shop/analytics'
      fullPath: '/shop/analytics'
      preLoaderRoute: typeof ShopAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/': {
      id: '/beheer/dashboard/'
      path: '/beheer/dashboard'
      fullPath: '/beheer/dashboard/'
      preLoaderRoute: typeof BeheerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmation/$bookingId': {
      id: '/book/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/book/confirmation/$bookingId'
      preLoaderRoute: typeof BookConfirmationBookingIdRouteImport
      parentRoute: typeof BookRoute
    }
    '/beheer/dashboard/users': {
      id: '/beheer/dashboard/users'
      path: '/beheer/dashboard/users'
      fullPath: '/beheer/dashboard/users'
      preLoaderRoute: typeof BeheerDashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/support': {
      id: '/beheer/dashboard/support'
      path: '/beheer/dashboard/support'
      fullPath: '/beheer/dashboard/support'
      preLoaderRoute: typeof BeheerDashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/shops': {
      id: '/beheer/dashboard/shops'
      path: '/beheer/dashboard/shops'
      fullPath: '/beheer/dashboard/shops'
      preLoaderRoute: typeof BeheerDashboardShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/settings': {
      id: '/beheer/dashboard/settings'
      path: '/beheer/dashboard/settings'
      fullPath: '/beheer/dashboard/settings'
      preLoaderRoute: typeof BeheerDashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/plans': {
      id: '/beheer/dashboard/plans'
      path: '/beheer/dashboard/plans'
      fullPath: '/beheer/dashboard/plans'
      preLoaderRoute: typeof BeheerDashboardPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/payments': {
      id: '/beheer/dashboard/payments'
      path: '/beheer/dashboard/payments'
      fullPath: '/beheer/dashboard/payments'
      preLoaderRoute: typeof BeheerDashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/logs': {
      id: '/beheer/dashboard/logs'
      path: '/beheer/dashboard/logs'
      fullPath: '/beheer/dashboard/logs'
      preLoaderRoute: typeof BeheerDashboardLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/dashboard/bookings': {
      id: '/beheer/dashboard/bookings'
      path: '/beheer/dashboard/bookings'
      fullPath: '/beheer/dashboard/bookings'
      preLoaderRoute: typeof BeheerDashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/ad/login': {
      id: '/beheer/ad/login'
      path: '/beheer/ad/login'
      fullPath: '/beheer/ad/login'
      preLoaderRoute: typeof BeheerAdLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookConfirmationBookingIdRoute: typeof BookConfirmationBookingIdRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookConfirmationBookingIdRoute: BookConfirmationBookingIdRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ShopAnalyticsRoute: ShopAnalyticsRoute,
  ShopCalendarRoute: ShopCalendarRoute,
  ShopCustomersRoute: ShopCustomersRoute,
  ShopNotificationsRoute: ShopNotificationsRoute,
  ShopPaymentsRoute: ShopPaymentsRoute,
  ShopServicesRoute: ShopServicesRoute,
  ShopSettingsRoute: ShopSettingsRoute,
  ShopStaffRoute: ShopStaffRoute,
  ShopIndexRoute: ShopIndexRoute,
  BeheerAdLoginRoute: BeheerAdLoginRoute,
  BeheerDashboardBookingsRoute: BeheerDashboardBookingsRoute,
  BeheerDashboardLogsRoute: BeheerDashboardLogsRoute,
  BeheerDashboardPaymentsRoute: BeheerDashboardPaymentsRoute,
  BeheerDashboardPlansRoute: BeheerDashboardPlansRoute,
  BeheerDashboardSettingsRoute: BeheerDashboardSettingsRoute,
  BeheerDashboardShopsRoute: BeheerDashboardShopsRoute,
  BeheerDashboardSupportRoute: BeheerDashboardSupportRoute,
  BeheerDashboardUsersRoute: BeheerDashboardUsersRoute,
  BeheerDashboardIndexRoute: BeheerDashboardIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
